// AUTO-GENERATED by scripts/build.ts from src/trains.yaml. Do not edit by hand.
"use strict";

(function () {
	const TAG = "[BasedGoat Trains]";

	const api = window.SubwayBuilderAPI;
	if (!api) {
		console.error(`${TAG} SubwayBuilderAPI not found.`);
		return;
	}

	// All rolling stock in this mod shares the same scissors-crossover speed cap.
	const STANDARD_CROSSOVER_SPEED = 6.7; // m/s (~15 mph)

	// Cost of transitioning between elevation profiles (tunnel portals, elevated ramps);
	// identical across every train type in this pack.
	const ELEVATION_TRANSITION_COSTS = {
		portalCost: 10000000, // surcharge per at-grade <-> cut-and-cover portal
		rampCost: 5000000,    // surcharge per at-grade <-> elevated ramp
	};

	const NO_GRADE_CROSSING = { allowGradeCrossing: false };

	// Heavy-rail (subway / commuter) grade crossing rules: lower combined-direction
	// TPH caps per road class, and highway crossings are always forbidden.
	const HEAVY_RAIL_GRADE_CROSSING = {
		allowGradeCrossing: true,
		gradeCrossingBaseCost: 300000,
		gradeCrossingMaintenancePerYear: 8000,
		gradeCrossingTphLimit: {
			highway: null,
			major: 15,
			medium: 18,
			minor: 21,
		},
	};

	// Light-rail grade crossing rules: cheaper maintenance and higher TPH caps than
	// heavy rail, reflecting shorter, lighter, more frequent street-running consists.
	const LIGHT_RAIL_GRADE_CROSSING = {
		allowGradeCrossing: true,
		gradeCrossingBaseCost: 300000,
		gradeCrossingMaintenancePerYear: 800,
		gradeCrossingTphLimit: {
			highway: null,
			major: 20,
			medium: 20,
			minor: 40,
		},
	};

	// Overrides applied to train types that ship with the base game.
	const MODIFIED_TRAIN_TYPES = [
	];

	// Brand-new train types added by this mod.
	const NEW_TRAIN_TYPES = [
		{
			id: "gsm",
			name: "Great Society Metro",
			description: "Generic heavy rail metro train based off Great Society Metro trains aswell as other modern heavy rail metros built afterwards in the U.S",
			stats: {
				maxSpeed: 31.3,
				maxAcceleration: 1.25,
				maxDeceleration: 0.98,
				maxLateralAcceleration: 1.63,
				maxSlopePercentage: 5.5,
				minTurnRadius: 45,
				parallelTrackSpacing: 3.76,
				trackClearance: 1.86,
				minStationTurnRadius: 900,
				maxSpeedLocalStation: 14,
				minCars: 4,
				maxCars: 8,
				carsPerCarSet: 2,
				capacityPerCar: 200,
				carLength: 22.86,
				trainWidth: 3.09,
				carCost: 2750000,
				minStationLength: 100,
				maxStationLength: 200,
				baseTrackCost: 35000,
				baseStationCost: 65000000,
				scissorsCrossoverCost: 18750000,
				trainOperationalCostPerHour: 215,
				carOperationalCostPerHour: 22,
				trackMaintenanceCostPerMeter: 360,
				stationMaintenanceCostPerYear: 320,
				stopTimeSeconds: 24,
				tphLimit: 42,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.6,
				STANDARD_TUNNEL: 2.02,
				CUT_AND_COVER: 1.01,
				AT_GRADE: 0.3,
				ELEVATED: 0.81,
				TRENCHED: 0.51,
				RAMP: 0.51,
			},
			compatibleTrackTypes: ["gsm"],
			appearance: {
				color: "#9D9F9C",
			},
			...ELEVATION_TRANSITION_COSTS,
			...NO_GRADE_CROSSING,
		},
		{
			id: "bart",
			name: "BART FOTF",
			description: "Fleet of the Future Rolling Stock",
			stats: {
				maxSpeed: 35.76,
				maxAcceleration: 1.34,
				maxDeceleration: 1.34,
				maxLateralAcceleration: 1.44,
				maxSlopePercentage: 4,
				minTurnRadius: 30,
				parallelTrackSpacing: 3.94,
				trackClearance: 1.95,
				minStationTurnRadius: 2300,
				maxSpeedLocalStation: 14,
				minCars: 2,
				maxCars: 10,
				carsPerCarSet: 2,
				capacityPerCar: 238,
				carLength: 21.34,
				trainWidth: 3.2,
				carCost: 2185366,
				minStationLength: 60,
				maxStationLength: 240,
				baseTrackCost: 55000,
				baseStationCost: 75000000,
				scissorsCrossoverCost: 15000000,
				trainOperationalCostPerHour: 195,
				carOperationalCostPerHour: 19.5,
				trackMaintenanceCostPerMeter: 300,
				stationMaintenanceCostPerYear: 320,
				stopTimeSeconds: 30,
				tphLimit: 24,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.9,
				STANDARD_TUNNEL: 2.09,
				CUT_AND_COVER: 1.04,
				AT_GRADE: 0.3,
				ELEVATED: 0.83,
				TRENCHED: 0.52,
				RAMP: 0.52,
			},
			compatibleTrackTypes: ["bart"],
			appearance: {
				color: "#0099D8",
			},
			...ELEVATION_TRANSITION_COSTS,
			...NO_GRADE_CROSSING,
		},
		{
			id: "s700",
			name: "S700 (High-Floor)",
			description: "High-Floor S700 (Mix of S200 and S700 Stats)",
			stats: {
				maxSpeed: 29,
				maxAcceleration: 1.34,
				maxDeceleration: 1.56,
				maxLateralAcceleration: 1.11,
				maxSlopePercentage: 10,
				minTurnRadius: 15,
				parallelTrackSpacing: 3.22,
				trackClearance: 1.59,
				minStationTurnRadius: 700,
				maxSpeedLocalStation: 6.7,
				minCars: 1,
				maxCars: 4,
				carsPerCarSet: 1,
				capacityPerCar: 170,
				carLength: 11.43,
				trainWidth: 2.65,
				carCost: 2089649,
				minStationLength: 11.43,
				maxStationLength: 51,
				baseTrackCost: 35000,
				baseStationCost: 63750000,
				scissorsCrossoverCost: 12750000,
				trainOperationalCostPerHour: 100,
				carOperationalCostPerHour: 5,
				stopTimeSeconds: 25,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.9,
				STANDARD_TUNNEL: 2.09,
				CUT_AND_COVER: 1.04,
				AT_GRADE: 0.3,
				ELEVATED: 0.83,
				TRENCHED: 0.52,
				RAMP: 0.52,
			},
			compatibleTrackTypes: ["bart", "caltrain"],
			appearance: {
				color: "#60fb87",
			},
			...ELEVATION_TRANSITION_COSTS,
			...LIGHT_RAIL_GRADE_CROSSING,
		},
		{
			id: "caltrain",
			name: "CalTrain KISS",
			description: "KISS",
			stats: {
				maxSpeed: 55.9,
				maxAcceleration: 1,
				maxDeceleration: 1.1,
				maxLateralAcceleration: 1.89,
				maxSlopePercentage: 4,
				minTurnRadius: 35,
				parallelTrackSpacing: 3.7,
				trackClearance: 1.83,
				minStationTurnRadius: 1600,
				maxSpeedLocalStation: 14,
				minCars: 2,
				maxCars: 8,
				carsPerCarSet: 1,
				capacityPerCar: 175,
				carLength: 25,
				trainWidth: 2.95,
				carCost: 3319612,
				minStationLength: 50,
				maxStationLength: 221,
				baseTrackCost: 25000,
				baseStationCost: 63750000,
				scissorsCrossoverCost: 12750000,
				trainOperationalCostPerHour: 500,
				carOperationalCostPerHour: 35,
				stopTimeSeconds: 40,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.9,
				STANDARD_TUNNEL: 2.09,
				CUT_AND_COVER: 1.04,
				AT_GRADE: 0.3,
				ELEVATED: 0.83,
				TRENCHED: 0.52,
				RAMP: 0.52,
			},
			compatibleTrackTypes: ["bart"],
			appearance: {
				color: "#F32F29",
			},
			...ELEVATION_TRANSITION_COSTS,
			...HEAVY_RAIL_GRADE_CROSSING,
		},
	];

	function registerTrains() {
		for (const { baseId, definition } of MODIFIED_TRAIN_TYPES) {
			api.trains.modifyTrainType(baseId, definition);
		}
		for (const definition of NEW_TRAIN_TYPES) {
			api.trains.registerTrainType(definition);
		}
	}

	api.hooks.onMapReady(registerTrains);
})();
