// AUTO-GENERATED by scripts/build.ts from src/trains.yaml. Do not edit by hand.
"use strict";

(function () {
	const TAG = "[BasedGoat Trains]";

	const api = window.SubwayBuilderAPI;
	if (!api) {
		console.error(`${TAG} SubwayBuilderAPI not found.`);
		return;
	}

	// All rolling stock in this mod shares the same scissors-crossover speed cap.
	const STANDARD_CROSSOVER_SPEED = 6.7; // m/s (~15 mph)

	// Cost of transitioning between elevation profiles (tunnel portals, elevated ramps);
	// identical across every train type in this pack.
	const ELEVATION_TRANSITION_COSTS = {
		portalCost: 10000000, // surcharge per at-grade <-> cut-and-cover portal
		rampCost: 5000000,    // surcharge per at-grade <-> elevated ramp
	};

	const NO_GRADE_CROSSING = { allowGradeCrossing: false };

	// Heavy-rail (subway / commuter) grade crossing rules: lower combined-direction
	// TPH caps per road class, and highway crossings are always forbidden.
	const HEAVY_RAIL_GRADE_CROSSING = {
		allowGradeCrossing: true,
		gradeCrossingBaseCost: 300000,
		gradeCrossingMaintenancePerYear: 8000,
		gradeCrossingTphLimit: {
			highway: null,
			major: 15,
			medium: 18,
			minor: 21,
		},
	};

	// Light-rail grade crossing rules: cheaper maintenance and higher TPH caps than
	// heavy rail, reflecting shorter, lighter, more frequent street-running consists.
	const LIGHT_RAIL_GRADE_CROSSING = {
		allowGradeCrossing: true,
		gradeCrossingBaseCost: 300000,
		gradeCrossingMaintenancePerYear: 800,
		gradeCrossingTphLimit: {
			highway: null,
			major: 20,
			medium: 20,
			minor: 40,
		},
	};

	// Overrides applied to train types that ship with the base game.
	const MODIFIED_TRAIN_TYPES = [
	];

	// Brand-new train types added by this mod.
	const NEW_TRAIN_TYPES = [
		{
			id: "gsm",
			name: "Great Society Metro",
			description: "Generic heavy rail metro train based off Great Society Metro trains aswell as other modern heavy rail metros built afterwards in the U.S",
			stats: {
				maxSpeed: 31.3,
				maxAcceleration: 1.25,
				maxDeceleration: 0.98,
				maxLateralAcceleration: 1.63,
				maxSlopePercentage: 5.5,
				minTurnRadius: 45,
				parallelTrackSpacing: 3.76,
				trackClearance: 1.86,
				minStationTurnRadius: 900,
				maxSpeedLocalStation: 14,
				minCars: 4,
				maxCars: 8,
				carsPerCarSet: 2,
				capacityPerCar: 200,
				carLength: 22.86,
				trainWidth: 3.09,
				carCost: 2750000,
				minStationLength: 100,
				maxStationLength: 200,
				baseTrackCost: 35000,
				baseStationCost: 65000000,
				scissorsCrossoverCost: 18750000,
				trainOperationalCostPerHour: 215,
				carOperationalCostPerHour: 22,
				trackMaintenanceCostPerMeter: 360,
				stationMaintenanceCostPerYear: 320,
				stopTimeSeconds: 24,
				tphLimit: 42,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.6,
				STANDARD_TUNNEL: 2.02,
				CUT_AND_COVER: 1.01,
				AT_GRADE: 0.3,
				ELEVATED: 0.81,
				TRENCHED: 0.51,
				RAMP: 0.51,
			},
			compatibleTrackTypes: ["gsm"],
			appearance: {
				color: "#9D9F9C",
			},
			...ELEVATION_TRANSITION_COSTS,
			...NO_GRADE_CROSSING,
		},
		{
			id: "bart",
			name: "BART FOTF",
			description: "Fleet of the Future Rolling Stock",
			stats: {
				maxSpeed: 35.76,
				maxAcceleration: 1.34,
				maxDeceleration: 1.34,
				maxLateralAcceleration: 1.44,
				maxSlopePercentage: 4,
				minTurnRadius: 30,
				parallelTrackSpacing: 3.94,
				trackClearance: 1.95,
				minStationTurnRadius: 2300,
				maxSpeedLocalStation: 14,
				minCars: 2,
				maxCars: 10,
				carsPerCarSet: 2,
				capacityPerCar: 238,
				carLength: 21.34,
				trainWidth: 3.2,
				carCost: 2185366,
				minStationLength: 60,
				maxStationLength: 240,
				baseTrackCost: 55000,
				baseStationCost: 75000000,
				scissorsCrossoverCost: 15000000,
				trainOperationalCostPerHour: 195,
				carOperationalCostPerHour: 19.5,
				trackMaintenanceCostPerMeter: 300,
				stationMaintenanceCostPerYear: 320,
				stopTimeSeconds: 30,
				tphLimit: 24,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.9,
				STANDARD_TUNNEL: 2.09,
				CUT_AND_COVER: 1.04,
				AT_GRADE: 0.3,
				ELEVATED: 0.83,
				TRENCHED: 0.52,
				RAMP: 0.52,
			},
			compatibleTrackTypes: ["bart"],
			appearance: {
				color: "#0099D8",
			},
			...ELEVATION_TRANSITION_COSTS,
			...NO_GRADE_CROSSING,
		},
		{
			id: "s700",
			name: "S700 (High-Floor)",
			description: "High-Floor S700 (Mix of S200 and S700 Stats)",
			stats: {
				maxSpeed: 29,
				maxAcceleration: 1.34,
				maxDeceleration: 1.56,
				maxLateralAcceleration: 1.11,
				maxSlopePercentage: 10,
				minTurnRadius: 15,
				parallelTrackSpacing: 3.22,
				trackClearance: 1.59,
				minStationTurnRadius: 700,
				maxSpeedLocalStation: 6.7,
				minCars: 1,
				maxCars: 4,
				carsPerCarSet: 1,
				capacityPerCar: 170,
				carLength: 11.43,
				trainWidth: 2.65,
				carCost: 2089649,
				minStationLength: 11.43,
				maxStationLength: 51,
				baseTrackCost: 35000,
				baseStationCost: 63750000,
				scissorsCrossoverCost: 12750000,
				trainOperationalCostPerHour: 100,
				carOperationalCostPerHour: 5,
				stopTimeSeconds: 25,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.9,
				STANDARD_TUNNEL: 2.09,
				CUT_AND_COVER: 1.04,
				AT_GRADE: 0.3,
				ELEVATED: 0.83,
				TRENCHED: 0.52,
				RAMP: 0.52,
			},
			compatibleTrackTypes: ["bart", "caltrain"],
			appearance: {
				color: "#60fb87",
			},
			...ELEVATION_TRANSITION_COSTS,
			...LIGHT_RAIL_GRADE_CROSSING,
		},
		{
			id: "caltrain",
			name: "CalTrain KISS",
			description: "KISS",
			stats: {
				maxSpeed: 55.9,
				maxAcceleration: 1,
				maxDeceleration: 1.1,
				maxLateralAcceleration: 1.89,
				maxSlopePercentage: 4,
				minTurnRadius: 35,
				parallelTrackSpacing: 3.7,
				trackClearance: 1.83,
				minStationTurnRadius: 1600,
				maxSpeedLocalStation: 14,
				minCars: 2,
				maxCars: 8,
				carsPerCarSet: 1,
				capacityPerCar: 175,
				carLength: 25,
				trainWidth: 2.95,
				carCost: 3319612,
				minStationLength: 50,
				maxStationLength: 221,
				baseTrackCost: 25000,
				baseStationCost: 63750000,
				scissorsCrossoverCost: 12750000,
				trainOperationalCostPerHour: 500,
				carOperationalCostPerHour: 35,
				stopTimeSeconds: 40,
				crossoverSpeed: STANDARD_CROSSOVER_SPEED,
			},
			elevationMultipliers: {
				DEEP_BORE: 4.9,
				STANDARD_TUNNEL: 2.09,
				CUT_AND_COVER: 1.04,
				AT_GRADE: 0.3,
				ELEVATED: 0.83,
				TRENCHED: 0.52,
				RAMP: 0.52,
			},
			compatibleTrackTypes: ["bart"],
			appearance: {
				color: "#F32F29",
			},
			...ELEVATION_TRANSITION_COSTS,
			...HEAVY_RAIL_GRADE_CROSSING,
		},
	];

	function registerTrains() {
		for (const { baseId, definition } of MODIFIED_TRAIN_TYPES) {
			api.trains.modifyTrainType(baseId, definition);
		}
		for (const definition of NEW_TRAIN_TYPES) {
			api.trains.registerTrainType(definition);
		}
	}

	api.hooks.onMapReady(registerTrains);
})();

// Custom-train editor: a toolbar panel for creating train types in-game.
//
// Compiled to plain JS and appended to index.js by scripts/build.ts. Mods are
// evaluated via `new Function()` with no import support, so this file is a
// script, not a module -- no imports, no exports, one self-contained IIFE.
//
// Types come from src/subway-builder.d.ts.
(function () {
    const TAG = "[BasedGoat Trains]";
    const STORAGE_KEY = "customTrains";
    const maybeApi = window.SubwayBuilderAPI;
    if (!maybeApi) {
        console.error(`${TAG} SubwayBuilderAPI not found.`);
        return;
    }
    // Re-bind non-optional: narrowing from the guard above doesn't reach the
    // hoisted function declarations further down.
    const api = maybeApi;
    // MUST run before the first `await`. The game resolves which mod is calling
    // from the synchronous call stack; after an await that context is gone and
    // storage calls would land in the wrong namespace (or nowhere).
    const store = api.storage.scoped();
    const h = api.utils.React.createElement;
    const { useState, useEffect } = api.utils.React;
    // Starting point for a new train: a generic heavy-rail metro. Every one of
    // the 28 required stats is present, so a half-filled form still produces a
    // valid train instead of NaN costs.
    const DEFAULT_STATS = {
        maxSpeed: 31.3,
        maxAcceleration: 1.25,
        maxDeceleration: 1.1,
        maxLateralAcceleration: 1.5,
        maxSlopePercentage: 4,
        maxSpeedLocalStation: 14,
        crossoverSpeed: 6.7,
        stopTimeSeconds: 30,
        minTurnRadius: 45,
        minStationTurnRadius: 900,
        parallelTrackSpacing: 3.76,
        trackClearance: 1.86,
        minCars: 4,
        maxCars: 8,
        carsPerCarSet: 2,
        capacityPerCar: 200,
        carLength: 22.86,
        trainWidth: 3.09,
        minStationLength: 100,
        maxStationLength: 200,
        carCost: 2500000,
        baseTrackCost: 35000,
        baseStationCost: 65000000,
        trainOperationalCostPerHour: 200,
        carOperationalCostPerHour: 20,
        trackMaintenanceCostPerMeter: 300,
        stationMaintenanceCostPerYear: 160000,
        tphLimit: 30,
    };
    const DEFAULT_ELEVATION = {
        DEEP_BORE: 4.9,
        STANDARD_TUNNEL: 2.09,
        CUT_AND_COVER: 1.04,
        AT_GRADE: 0.3,
        ELEVATED: 0.83,
        TRENCHED: 0.52,
        RAMP: 0.52,
    };
    // Drives the form layout. Adding a stat here is the only edit needed to
    // expose it -- the inputs are generated from this list.
    const STAT_GROUPS = [
        {
            title: "Performance",
            keys: [
                "maxSpeed",
                "maxAcceleration",
                "maxDeceleration",
                "maxLateralAcceleration",
                "maxSlopePercentage",
                "maxSpeedLocalStation",
                "crossoverSpeed",
                "stopTimeSeconds",
            ],
        },
        {
            title: "Track geometry",
            keys: ["minTurnRadius", "minStationTurnRadius", "parallelTrackSpacing", "trackClearance"],
        },
        {
            title: "Rolling stock",
            keys: [
                "minCars",
                "maxCars",
                "carsPerCarSet",
                "capacityPerCar",
                "carLength",
                "trainWidth",
                "minStationLength",
                "maxStationLength",
            ],
        },
        {
            title: "Costs",
            keys: [
                "carCost",
                "baseTrackCost",
                "baseStationCost",
                "trainOperationalCostPerHour",
                "carOperationalCostPerHour",
                "trackMaintenanceCostPerMeter",
                "stationMaintenanceCostPerYear",
                "tphLimit",
            ],
        },
    ];
    function newDraft() {
        return {
            id: "",
            name: "",
            description: "",
            color: "#60fb87",
            trackTypes: "",
            stats: { ...DEFAULT_STATS },
        };
    }
    function toDefinition(draft) {
        const trackTypes = draft.trackTypes
            .split(",")
            .map((t) => t.trim())
            .filter((t) => t.length > 0);
        return {
            id: draft.id,
            name: draft.name,
            description: draft.description,
            stats: { ...draft.stats },
            compatibleTrackTypes: trackTypes.length > 0 ? trackTypes : [draft.id],
            appearance: { color: draft.color },
            elevationMultipliers: { ...DEFAULT_ELEVATION },
        };
    }
    /** Returns an error message, or null when the draft is good. */
    function validate(draft) {
        if (!/^[a-z0-9-]+$/.test(draft.id)) {
            return "ID must be lowercase letters, numbers and dashes only.";
        }
        if (draft.name.trim().length === 0)
            return "Name is required.";
        for (const [key, value] of Object.entries(draft.stats)) {
            if (!Number.isFinite(value))
                return `${key} must be a number.`;
        }
        return null;
    }
    // ---------------------------------------------------------------------
    // Persistence
    // ---------------------------------------------------------------------
    async function loadSaved() {
        return await store.get(STORAGE_KEY, []);
    }
    /** Persists and reports whether the write actually stuck. */
    async function persist(trains) {
        await store.set(STORAGE_KEY, trains);
        // Browser builds make every storage call a silent no-op, so confirm the
        // key exists rather than trusting set() to have done something.
        const keys = await store.keys();
        return keys.indexOf(STORAGE_KEY) !== -1;
    }
    function register(definition) {
        api.trains.registerTrainType(definition);
    }
    // Re-register saved trains on every load. registerTrainType replaces an
    // existing id wholesale, so this is safe to run repeatedly.
    api.hooks.onMapReady(() => {
        void loadSaved().then((trains) => {
            for (const train of trains)
                register(train);
            if (trains.length > 0)
                console.log(`${TAG} restored ${trains.length} custom train(s).`);
        });
    });
    // ---------------------------------------------------------------------
    // UI
    // ---------------------------------------------------------------------
    function readNumber(event) {
        const value = event.target.value;
        return value === "" ? NaN : Number(value);
    }
    function readText(event) {
        return event.target.value;
    }
    const INPUT_CLASS = "w-full rounded border border-input bg-background px-2 py-1 text-sm";
    function textField(key, label, value, onChange, placeholder) {
        return h("label", { key, className: "block space-y-1" }, [
            h("span", { key: "l", className: "text-xs text-muted-foreground" }, label),
            h("input", {
                key: "i",
                type: "text",
                className: INPUT_CLASS,
                value,
                placeholder: placeholder ?? "",
                onChange: (e) => onChange(readText(e)),
            }),
        ]);
    }
    function TrainEditorPanel() {
        const [saved, setSaved] = useState([]);
        const [draft, setDraft] = useState(newDraft);
        const [status, setStatus] = useState("");
        useEffect(() => {
            void loadSaved().then(setSaved);
        }, []);
        function setStat(key, value) {
            setDraft((prev) => ({ ...prev, stats: { ...prev.stats, [key]: value } }));
        }
        async function onSave() {
            const error = validate(draft);
            if (error) {
                setStatus(error);
                return;
            }
            const definition = toDefinition(draft);
            const next = saved.filter((t) => t.id !== definition.id).concat(definition);
            register(definition);
            const stuck = await persist(next);
            setSaved(next);
            setDraft(newDraft());
            setStatus("");
            api.ui.showNotification(stuck
                ? `Saved "${definition.name}".`
                : `Registered "${definition.name}", but storage is unavailable — it will be gone after a reload.`, stuck ? "success" : "warning");
        }
        async function onDelete(id) {
            const next = saved.filter((t) => t.id !== id);
            await persist(next);
            setSaved(next);
            // There is no unregisterTrainType, so the type stays live this session.
            api.ui.showNotification("Deleted. Reload the game to clear it from the picker.", "info");
        }
        const savedList = saved.length === 0
            ? [h("p", { key: "none", className: "text-xs text-muted-foreground" }, "No custom trains yet.")]
            : saved.map((train) => h("div", { key: train.id, className: "flex items-center justify-between gap-2" }, [
                h("span", { key: "n", className: "flex items-center gap-2 text-sm" }, [
                    h("span", {
                        key: "dot",
                        className: "inline-block h-3 w-3 rounded-full",
                        style: { backgroundColor: train.appearance.color },
                    }),
                    train.name,
                ]),
                h("button", {
                    key: "d",
                    className: "text-xs text-destructive underline",
                    onClick: () => void onDelete(train.id),
                }, "Delete"),
            ]));
        const statInputs = STAT_GROUPS.map((group) => h("div", { key: group.title, className: "space-y-2" }, [
            h("h4", { key: "t", className: "text-xs font-semibold uppercase text-muted-foreground" }, group.title),
            h("div", { key: "g", className: "grid grid-cols-2 gap-2" }, group.keys.map((key) => h("label", { key, className: "block space-y-1" }, [
                h("span", { key: "l", className: "text-xs text-muted-foreground" }, key),
                h("input", {
                    key: "i",
                    type: "number",
                    step: "any",
                    className: INPUT_CLASS,
                    value: String(draft.stats[key]),
                    onChange: (e) => setStat(key, readNumber(e)),
                }),
            ]))),
        ]));
        return h("div", { className: "space-y-4 p-4" }, [
            h("section", { key: "saved", className: "space-y-2" }, [
                h("h3", { key: "t", className: "text-sm font-semibold" }, "Custom trains"),
                ...savedList,
            ]),
            h("hr", { key: "sep", className: "border-border" }),
            h("section", { key: "form", className: "space-y-3" }, [
                h("h3", { key: "t", className: "text-sm font-semibold" }, "Add a train"),
                textField("id", "ID (lowercase, no spaces)", draft.id, (v) => setDraft((p) => ({ ...p, id: v })), "my-train"),
                textField("name", "Name", draft.name, (v) => setDraft((p) => ({ ...p, name: v })), "My Train"),
                textField("desc", "Description", draft.description, (v) => setDraft((p) => ({ ...p, description: v }))),
                textField("color", "Colour (hex)", draft.color, (v) => setDraft((p) => ({ ...p, color: v })), "#60fb87"),
                textField("tracks", "Compatible track types (comma separated, blank = its own)", draft.trackTypes, (v) => setDraft((p) => ({ ...p, trackTypes: v })), "bart, caltrain"),
                ...statInputs,
                status.length > 0
                    ? h("p", { key: "err", className: "text-xs text-destructive" }, status)
                    : null,
                h("button", {
                    key: "save",
                    className: "w-full rounded bg-primary px-3 py-2 text-sm text-primary-foreground",
                    onClick: () => void onSave(),
                }, "Save train"),
            ]),
        ]);
    }
    api.ui.addToolbarPanel({
        id: "basedgoat-train-editor",
        icon: "Train",
        tooltip: "Custom Trains",
        title: "Custom Trains",
        width: 420,
        // Passing the component rather than calling it: hooks are only legal
        // inside a component React itself renders.
        render: () => h(TrainEditorPanel),
    });
})();
